# Generated by Django 2.2.7 on 2019-11-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpulseEngine',
            fields=[
                ('impulse_engine_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mass', models.IntegerField()),
                ('energy_cost', models.IntegerField()),
                ('max_accel', models.IntegerField()),
                ('repair_cost', models.IntegerField()),
            ],
        ),
    ]
