# Generated by Django 3.0.2 on 2020-01-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmmunitionModel',
            fields=[
                ('ammunition_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mass', models.IntegerField()),
                ('repair_cost', models.IntegerField()),
                ('damage_type', models.IntegerField()),
                ('ammunition_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ArmourModel',
            fields=[
                ('armour_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mass', models.IntegerField()),
                ('repair_cost', models.IntegerField()),
                ('armour_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('computer_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mass', models.IntegerField()),
                ('repair_cost', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JumpDriveModel',
            fields=[
                ('jump_drive_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mass', models.IntegerField()),
                ('energy_cost', models.IntegerField()),
                ('repair_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RadarModel',
            fields=[
                ('radar_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mass', models.IntegerField()),
                ('energy_cost', models.IntegerField()),
                ('repair_cost', models.IntegerField()),
                ('tracking_styel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShipTypeModel',
            fields=[
                ('ship_type_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('weight', models.IntegerField()),
                ('power_gen', models.IntegerField()),
                ('battery_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeaponModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mass', models.IntegerField()),
                ('energy_cost', models.IntegerField()),
                ('repair_cost', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('munition_velocity', models.IntegerField()),
                ('ammunition_type', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ImpulseEngine',
            new_name='ImpulseEngineModel',
        ),
    ]
