# Generated by Django 3.0.2 on 2020-02-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200201_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionmodel',
            name='action_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ammunitionmodel',
            name='ammunition_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='armourmodel',
            name='armour_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='computermodel',
            name='computer_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='conditionmodel',
            name='condition_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='impulseenginemodel',
            name='impulse_engine_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jumpdrivemodel',
            name='jump_drive_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='radarmodel',
            name='radar_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shipmodel',
            name='ship_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shiptypemodel',
            name='ship_type_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subroutinemodel',
            name='subroutine_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
