# Generated by Django 3.0.2 on 2020-02-13 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200205_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionmodel',
            name='component_type',
        ),
        migrations.RemoveField(
            model_name='shipmodel',
            name='health',
        ),
        migrations.AddField(
            model_name='actionmodel',
            name='ammunition_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actionmodel',
            name='component_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ammunitionmodel',
            name='max_ammunition',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conditionmodel',
            name='name',
            field=models.CharField(choices=[('AL', 'AmmunitionLevel'), ('DI', 'Distance'), ('EL', 'EnergyLevel'), ('HE', 'Health'), ('ID', 'IsDisabled')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiptypemodel',
            name='health',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actionmodel',
            name='name',
            field=models.CharField(choices=[('AR', 'AttemptRepairs'), ('DE', 'Delay'), ('FI', 'FireImpulse'), ('FW', 'FireWeapon'), ('JU', 'Jump'), ('SC', 'Scan')], max_length=100),
        ),
        migrations.RemoveField(
            model_name='actionmodel',
            name='subroutines',
        ),
        migrations.AddField(
            model_name='actionmodel',
            name='subroutines',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.SubroutineModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conditionmodel',
            name='target',
            field=models.IntegerField(blank=True, choices=[(0, 'SELF'), (1, 'ENEMY')], null=True),
        ),
    ]
