# Generated by Django 3.0.2 on 2020-02-13 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200212_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmodel',
            name='max_energy',
        ),
    ]
