# Generated by Django 3.0.2 on 2020-03-29 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_shipmodel_max_energy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionmodel',
            old_name='subroutines',
            new_name='subroutine',
        ),
    ]
