# Generated by Django 3.0.2 on 2020-04-13 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200409_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subroutinemodel',
            name='ship',
        ),
        migrations.CreateModel(
            name='ProgramModel',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CharacterModel')),
                ('ship_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ShipModel')),
            ],
        ),
        migrations.AddField(
            model_name='subroutinemodel',
            name='program',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.ProgramModel'),
            preserve_default=False,
        ),
    ]
