# Generated by Django 3.0.2 on 2020-04-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200413_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmodel',
            old_name='character_id',
            new_name='character',
        ),
        migrations.RenameField(
            model_name='programmodel',
            old_name='ship_id',
            new_name='ship',
        ),
    ]
