# Generated by Django 3.0.2 on 2020-04-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200413_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmodel',
            old_name='profile_id',
            new_name='program_id',
        ),
    ]
