# Generated by Django 3.0.2 on 2020-04-13 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200413_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmodel',
            name='ship',
        ),
        migrations.AddField(
            model_name='shipmodel',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ProgramModel'),
        ),
    ]
