# Generated by Django 3.0.2 on 2020-04-13 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200413_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionmodel',
            name='ammunition_name',
        ),
        migrations.AddField(
            model_name='programmodel',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmodel',
            name='armour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ArmourModel'),
            preserve_default=False,
        ),
    ]
